language: node_js  #设置语言

node_js: stable  #设置相应的版本

# Travis-CI Caching  缓存
cache:
    directories:
        - node_modules

before_install:
    - export TZ='Asia/Shanghai' # 更改时区

install:
  - npm install  #安装hexo及插件

script:
  - hexo clean  #清除
  - hexo g && gulp  #生成

after_script:
  - git clone https://${GH_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/   # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd ./public
  - git config user.name "{GH_Name}"  #修改name
  - git config user.email "{GH_Name}"  #修改email
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${GH_Token}@${GH_REF}" master:${GH_fz}

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/HiMrHu/H.git  #设置GH_REF